Repository Virtual4087/Tree2Hope, pull requests merged in 2023-10, with the labels that each got.

#15 Fix overflow in Where we plant section
  index.html
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#24 Closes #20
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#32 issueSolved
  assets/css/style.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#30 feat:" Add CONTRIBUTING.md"
  CONTRIBUTING.md
Labels: hacktoberfest, hacktoberfest-accepted

#38 Updated README.md
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#37 Social media icon
  assets/css/style.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#47 issueSolved for responsiveness in small size mobile
  assets/css/responsiveness.css
  assets/css/style.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#62 Fixed footer for mobile view
  assets/css/responsiveness.css
  assets/css/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#63 The popup is styled now and it is added at the required places
  assets/css/style.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#69 Improved the spacing between the links in the footer , Fixes : #65
  assets/css/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#75 Implement automatic commenting when an issue or pr is opened
  .github/workflows/greetings.yml
Labels: hacktoberfest, hacktoberfest-accepted

#74 Readme
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#77 fixed contact us text wrapping issue
  assets/css/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#82 github icon on footer
  about.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#84 Added the missing Menu Bar in the About Page
  about.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#92 :sparkles:[feat][combined context and image into one container and applied styles ]
  about.html
  assets/css/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#96 Added relevant text in about us page
  about.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#97 Added links to the countries
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#104 added bold tag in heading
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023
